[option]
exclude_paths = []
indent = 4

[rules]
default_nettype_none = true
enum_with_type = true

case_default = true
explicit_case_default = true
explicit_if_else = true

function_same_as_system_function = true
function_with_automatic = true

inout_with_tri = true
input_with_var = true
output_with_var = true
interface_port_with_modport = true

localparam_explicit_type = true
localparam_type_twostate = true
parameter_explicit_type = true
parameter_in_package = true
parameter_type_twostate = true

loop_variable_declaration = true
non_ansi_module = true

non_blocking_assignment_in_always_comb = true
blocking_assignment_in_always_ff = true

# sequential_block_in_always_comb = true
# sequential_block_in_always_ff = true
# sequential_block_in_always_latch = true

keyword_forbidden_always = true
keyword_forbidden_priority = true
keyword_forbidden_unique0 = true
keyword_forbidden_unique = true
keyword_forbidden_wire_reg = false

style_keyword_construct = true
style_keyword_end = true
style_keyword_newline = true
